# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:30+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class MediaMetadata(BaseModel):
    format: Optional[str] = None
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class MediaItem(BaseModel):
    caption: Optional[str] = None
    copyright: Optional[str] = None
    media_metadata: Optional[MediaMetadata] = Field(None, alias='media-metadata')
    subtype: Optional[str] = None
    type: Optional[str] = None


class DesFacet(RootModel[Union[List, str]]):
    root: Union[List, str]


class GeoFacet1(Enum):
    field_ = ''


class GeoFacet(RootModel[Optional[Union[Union[List, GeoFacet1], GeoFacet1]]]):
    root: Optional[Union[Union[List, GeoFacet1], GeoFacet1]] = None


class OrgFacet(RootModel[Optional[List]]):
    root: Optional[List] = None


class PerFacet(RootModel[Optional[List]]):
    root: Optional[List] = None


class Section(Enum):
    Arts = 'Arts'
    Automobiles = 'Automobiles'
    Blogs = 'Blogs'
    Books = 'Books'
    Business_Day = 'Business Day'
    Education = 'Education'
    Fashion___Style = 'Fashion & Style'
    Food = 'Food'
    Health = 'Health'
    Job_Market = 'Job Market'
    Magazine = 'Magazine'
    membercenter = 'membercenter'
    Movies = 'Movies'
    Multimedia = 'Multimedia'
    N_Y__20_2F_20Region = 'N.Y.%20%2F%20Region'
    NYT_Now = 'NYT Now'
    Obituaries = 'Obituaries'
    Open = 'Open'
    Opinion = 'Opinion'
    Public_Editor = 'Public Editor'
    Real_Estate = 'Real Estate'
    Science = 'Science'
    Sports = 'Sports'
    Style = 'Style'
    Sunday_Review = 'Sunday Review'
    T_Magazine = 'T Magazine'
    Technology = 'Technology'
    The_Upshot = 'The Upshot'
    Theater = 'Theater'
    Times_Insider = 'Times Insider'
    Today_s_Paper = 'Today’s Paper'
    Travel = 'Travel'
    U_S_ = 'U.S.'
    World = 'World'
    Your_Money = 'Your Money'
    all_sections = 'all-sections'


class TimePeriod(Enum):
    field_1 = '1'
    field_7 = '7'
    field_30 = '30'


class Article(BaseModel):
    abstract: Optional[str] = None
    byline: Optional[str] = None
    column: Optional[str] = None
    des_facet: Optional[DesFacet] = None
    geo_facet: Optional[GeoFacet] = None
    media: Optional[Union[List, str]] = None
    org_facet: Optional[OrgFacet] = None
    per_facet: Optional[PerFacet] = None
    published_date: Optional[str] = None
    section: Optional[str] = None
    source: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None


class ArticleWithCountType(BaseModel):
    abstract: Optional[str] = None
    byline: Optional[str] = None
    column: Optional[str] = None
    count_type: Optional[str] = None
    des_facet: Optional[DesFacet] = None
    geo_facet: Optional[GeoFacet] = None
    media: Optional[List[MediaItem]] = None
    org_facet: Optional[OrgFacet] = None
    per_facet: Optional[PerFacet] = None
    published_date: Optional[str] = None
    section: Optional[str] = None
    source: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None
