# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:44:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel

from . import Article


class JsonGetResponse(BaseModel):
    copyright: Optional[str] = None
    errors: Optional[List[str]] = None
    results: Optional[List] = None
    status: Optional[str] = None


class JsonGetResponseModel(BaseModel):
    copyright: Optional[str] = None
    num_results: Optional[int] = None
    results: Optional[List[Article]] = None
    status: Optional[str] = None
